Add config system and some optimizations
MaskDuck/impostor-helper-bot pull request #13
Opened 2022-08-01 16:56 UTC by VaibhavSys

2022-08-01 17:05 UTC, VaibhavSys commented
Config file could have been made better however, I wasn't able to categorize them.

2022-08-02 01:11 UTC, AceyDoCodes commented
use pydantic for config its better to work with tbh

2022-08-02 07:16 UTC, VaibhavSys commented
> use pydantic for config its better to work with tbh

I believe that something minimal and simple like TOML would be way better as there is no need of complexity in this.

2022-08-02 09:49 UTC, MaskDuck requested changes

2022-08-02 09:49 UTC, MaskDuck commented on src/exts/suggestion.py
> +        channel = self.suggestion_channel
suggestion_channel is an int. we cant interact with an int.

2022-08-02 09:49 UTC, MaskDuck commented on src/exts/bans.py
> +        self.UNBANNED_CHANNEL_ID = self.bot.config["unbanned_channel"]
typehint these with typing.Final[int]

2022-08-02 09:49 UTC, MaskDuck commented on src/__main__.py
> +        config = parse(config_file.read())
```suggestion
        self.config = parse(config_file.read())
```

2022-08-02 12:09 UTC, AceyDoCodes commented
> > use pydantic for config its better to work with tbh
> 
> I believe that something minimal and simple like TOML would be way better as there is no need of complexity in this.

its not that complicated :/ you just install pydantic subclass pydantic.BaseModel and add some shts and boom just use the class

2022-08-02 12:12 UTC, VaibhavSys commented
> > > use pydantic for config its better to work with tbh
> > 
> > 
> > I believe that something minimal and simple like TOML would be way better as there is no need of complexity in this.
> 
> its not that complicated :/ you just install pydantic subclass pydantic.BaseModel and add some shts and boom just use the class

TOML is simple, just whats needed for *this*. Pydantic would be too complex for *this* I believe.

2022-08-02 12:13 UTC, VaibhavSys commented on src/exts/suggestion.py
> +        channel = self.suggestion_channel
[05e5d0a](https://github.com/MaskDuck/impostor/pull/13/commits/05e5d0af3faf9af68a830f127b0fd1c6a7da7782)

2022-08-02 12:35 UTC, VaibhavSys commented on src/__main__.py
> +        config = parse(config_file.read())
The `config` dict is already on the `bot` object.

2022-08-02 13:03 UTC, MaskDuck commented on src/exts/bans.py
> +        self.UNBANNED_CHANNEL_ID: int = self.bot.config["unbanned_channel"]
```suggestion
        self.MAIN_SERVER_ID: Final[int] = self.bot.config["main_server"]
        self.APPEAL_SERVER_ID: Final[int] = self.bot.config["appeal_server"]
        self.APPEAL_CHANNEL_ID: Final[int] = self.bot.config["appeal_channel"]
        self.UNBANNED_CHANNEL_ID: Final[int] = self.bot.config["unbanned_channel"]
```

2022-08-02 13:05 UTC, MaskDuck requested changes
also it would be nice to use pydantic tbh.

2022-08-02 13:05 UTC, MaskDuck commented on src/exts/suggestion.py
> +        channel = self.suggestion_channel
i've already said, suggestion_channel is an int. we're interact with channel directly.

2022-08-02 13:06 UTC, MaskDuck commented on src/__main__.py
> +        self.config = parse(config_file.read())
```suggestion
        config = parse(config_file.read())
```

2022-08-02 13:15 UTC, VaibhavSys commented on src/exts/suggestion.py
> +        channel = self.suggestion_channel
then line 57 would be invalidiated and would have to get the channel again. Currently, it is going to get that channel and use the channel object so it should work.

2022-08-05 11:54 UTC, MaskDuck commented on src/exts/suggestion.py
> +        channel = self.suggestion_channel
```suggestion
        channel = interaction.guild.get_channel(self.suggestion_channel)
```

2022-08-05 11:54 UTC, MaskDuck approved these changes
lgtm

2022-08-05 11:56 UTC, merged